-- 내 화장대 예시 게시글 (자동 생성: npm run seed:sql)
-- Supabase SQL Editor 에 붙여넣고 실행하세요. 같은 id 는 건너뜁니다.
-- 화면에는 "예시 글" 배지가 붙어 실제 사용자 후기와 구분됩니다.
begin;

insert into public.board_posts (id,user_id,author_nickname,concern_category,title,body,product_name,verdict,image_url,likes,created_at) values ('seed-01',null,'민감이(예시)','barrier','따가운 시기엔 이것만 남겼어요','환절기마다 볼이 붉어져서 루틴을 토너-크림 두 단계로 줄였어요. 판테놀이랑 세라마이드 들어간 크림만 남기고 나머지는 2주 쉬었더니 따가움이 덜해진 느낌이었어요. 개인차가 있을 테니 참고만 해주세요.','세라마이드 장벽 크림 (유형)','good',null,24,'2026-09-29T12:12:00.000Z') on conflict (id) do nothing;
insert into public.board_posts (id,user_id,author_nickname,concern_category,title,body,product_name,verdict,image_url,likes,created_at) values ('seed-02',null,'지성러(예시)','sebum','BHA 패드 격일로 바꿨더니','매일 쓰다가 턱 쪽이 각질처럼 일어나서 격일로 줄였어요. 번들거림은 비슷한데 따가운 게 사라져서 이 정도가 저한테 맞는 것 같아요. 저녁에만 쓰고 아침엔 선크림 꼭 챙기고 있어요.','BHA 토너 패드 (유형)','soso',null,11,'2026-09-28T00:12:00.000Z') on conflict (id) do nothing;
insert into public.board_posts (id,user_id,author_nickname,concern_category,title,body,product_name,verdict,image_url,likes,created_at) values ('seed-03',null,'잡티고민중(예시)','pigmentation','비타민C 세럼 3주차 솔직 후기','아침에 비타민C, 저녁에 나이아신아마이드로 나눠 썼어요. 잡티가 드라마틱하게 없어지진 않았지만 전체 톤이 조금 균일해진 느낌. 처음 며칠은 살짝 따끔했는데 지금은 괜찮아요. 개인 후기예요.','비타민C 세럼 (유형)','good',null,37,'2026-09-27T05:12:00.000Z') on conflict (id) do nothing;
insert into public.board_posts (id,user_id,author_nickname,concern_category,title,body,product_name,verdict,image_url,likes,created_at) values ('seed-04',null,'건조사막(예시)','dryness','히알루론산 세럼만으론 부족했어요','수분 세럼을 세 겹 발라도 당김이 계속됐는데, 마지막에 오일 한두 방울 섞어 크림을 바르니 아침까지 촉촉했어요. 여러 겹보다 마무리 한 단계가 저한텐 중요했나 봐요.','히알루론산 수분 세럼 (유형)','soso',null,15,'2026-09-26T13:12:00.000Z') on conflict (id) do nothing;
insert into public.board_posts (id,user_id,author_nickname,concern_category,title,body,product_name,verdict,image_url,likes,created_at) values ('seed-05',null,'레티놀초보(예시)','firming','레티놀 시작하고 각질 폭발… 이렇게 버텼어요','주 2회부터 시작했는데도 2주째 각질이 심했어요. AHA 토너를 같이 쓰고 있었던 게 문제였던 것 같아서 토너를 빼고 세라마이드 크림을 두껍게 발랐더니 3주차부터 안정됐어요. 심하면 꼭 전문가와 상담하세요.','레티놀 크림 (유형)','bad',null,42,'2026-09-24T10:12:00.000Z') on conflict (id) do nothing;
insert into public.board_posts (id,user_id,author_nickname,concern_category,title,body,product_name,verdict,image_url,likes,created_at) values ('seed-06',null,'결고민(예시)','texture','PHA 토너로 갈아탄 이유','AHA 는 저한테 너무 따가워서 PHA 로 바꿨어요. 확실히 순한 대신 변화도 천천히 오는 느낌. 한 달 정도 쓰니 코 옆 결이 살짝 매끈해진 것 같아요.','PHA 토너 (유형)','good',null,8,'2026-09-22T02:12:00.000Z') on conflict (id) do nothing;
insert into public.board_posts (id,user_id,author_nickname,concern_category,title,body,product_name,verdict,image_url,likes,created_at) values ('seed-07',null,'칙칙탈출(예시)','dullness','갈락토미세스 에센스 한 달','아침 세안 후 첫 단계로 썼어요. 화장이 좀 더 잘 먹는 느낌은 있는데 톤 자체가 밝아졌는지는 잘 모르겠어요. 향이 발효 냄새라 호불호 있을 듯.','갈락토미세스 발효 에센스 (유형)','soso',null,6,'2026-09-19T23:12:00.000Z') on conflict (id) do nothing;
insert into public.board_posts (id,user_id,author_nickname,concern_category,title,body,product_name,verdict,image_url,likes,created_at) values ('seed-08',null,'트러블졸업희망(예시)','breakout','어성초 토너 + 시카 크림 조합','트러블 올라올 때 자극 없이 진정시키는 용도로만 써요. 없애주는 느낌은 아니고 덜 붉어지는 정도. 티트리 제품은 저한텐 너무 건조해서 뺐어요.','어성초 진정 토너 (유형)','good',null,19,'2026-09-17T08:12:00.000Z') on conflict (id) do nothing;

commit;
